### ISSUE TITLE
Deep Evolution

### ISSUE THREAD

**Issue by waudinio27** [entrpn/fingym#4]
Dear Fingym Team! 

I am delighted by the Deep Evolution Agent. 
Is there a chance that a version for Forex gets published? 
It should be able to do short trading, and the Environment should limit the agent to only buy, sell or  hold one unit at each step. Like this it will be easier to adopt it for Live Trading.

Best regards and keep up the great work!

Matthias

**Comment by entrpn** [comment]
Hey Matthias,

Thanks for the feedback.

You can configure the deep evolution agent to trade one unit at a time via the config value

```
'max_shares_to_trade_at_once': 1
```

There is a backlog item to implement short selling in the environments, however, there are no plans to implement a forex environment at the moment. However, I'll add it to the backlog and see when we can get to it. And to be completely honest and transparent, I'm not sure when either of these will be done.

If you want to make one and create a pull request, I would merge it into the codebase. 

To allow short selling, look at the class SpyEnv in `https://github.com/entrpn/fingym/blob/master/gym/envs/spy_envs.py` the _trade method needs to be modified to allow short selling.

For forex, create another environment that extends SpyEnv and override the _load_data() function to pass the forex data.
